### ISSUE TITLE
Startup Care Package + Paddle analytics

### ISSUE THREAD

**Issue by FabioVirgi** [BrightCanopy/startup-tools#3]
Paddle.com recently published a Startup Care Package which provides $4000 of startup resources for free.

It includes brands like Digital Ocean, Zapier, Trello, Olark and more. You can find it here: http://startups.paddle.com

Feel free to consider adding Paddle to the list too. We offer a payments platform (one-time & subscriptions) that handles everything from taxes and order fulfilment to international taxes and customer support, taking away the burden from startups. 

Feel free to email me at fabio@paddle.com if you'd like some more info! :)

**Comment by BrightCanopy** [comment]
Thanks Fabio,

I've added both the Startup Care package and the Paddle itself.
I love the way you've presented the care package, beautifully done.

-bill

**Comment by FabioVirgi** [comment]
Thanks for including us on there Bill! Much appreciated :)
